name: Publish Blog with Hugo
on:
  push:
    branches:
    - master
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Checkout master
      uses: actions/checkout@v1

    - name: Build and publish blog
      env:
        HUGO_VERSION: 0.58.2
        TARGET_REPO: polothy/polothy.github.io
        TOKEN: ${{ secrets.TOKEN }}
      run: |
        scripts/action.sh
